import Template2 from "@/components/components-ui/UI/Template2";
import ClientAuth from "./ClientAuth";
import ServerAuth from "./ServerAuth";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default async function RootLayout({
  children,
  ...rest
}: {
  children: React.ReactNode;
}) {
  return (
    <Template2>
      <ServerAuth>
        <ClientAuth>{children}</ClientAuth>
      </ServerAuth>
    </Template2>
  );
}
